### ISSUE TITLE
Initial ortho set extremly slow to download

### ISSUE THREAD

**Issue by expataviator** [kubilus1/autoortho#421]
**Describe the bug**
Trying to download the north american ortho set as part of initial setup and the download speed is 0.45Mbps. If I type the file URL into Chrome it downloads very fast. 

Windows 11

**Comment by ukflyer** [comment]
same for Euro set whats going on?

**Comment by sinistre1973** [comment]
Here too...Very slow

**Comment by sanderdatema** [comment]
When using an older commit, the speed is fine. So somehow something has changed in the download method...

**Comment by mercster** [comment]
I'm noticing some very slow speeds, worse than that.  North America was actually decent speed, around 4Mbps.  But then I've moved on to Europe and Africa, which are moving at a snails pace of 0.5-0.8Mbps.  I have a feeling Github is beginning to throttle these?  I'm not sure github is the best place to host these multi-gigabyte files.  This is 0.70 of AutoOrtho.  Cool product but these download speeds are pretty bad.  Surely there's a better place to host these files?

**Comment by ukflyer** [comment]
going back to 0.6.0 works well, sticking with this until 0.7.0 is fixed

**Comment by davlaw** [comment]
Ya been running the last 4 hours or so for NA

**Comment by kubilus1** [comment]
Yeah, I think there is something up with how often it's attempting to show progress.  Fix incoming ....

**Comment by rheesbirman** [comment]
Hi, unfortunately this is still happening in v7.0.1
I get a good speed for a while, then it drops down to less than 0.5MBs and stays there.
![autoortho_win_8ftMBLdisr](https://github.com/kubilus1/autoortho/assets/72471443/d559b555-fc75-4536-9aa3-18417175faa7)
